version: "3.8"

services:
  postgres:
    container_name: postgres-ola-hr-api
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: ola-hr_api_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/ola-hr-api
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data/postgres-ola-hr-api
    ports:
      - "5435:5432"
    networks:
      - local
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ola-hr_api_db -U postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    container_name: adminer-ola-hr-api
    image: adminer
    ports:
      - "7001:8080"
    networks:
      - local

networks:
  local:
    driver: bridge